name: CI

on: 
  push:
    branches-ignore:    
      - 'dependabot/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
